In [1]:
def soma_dois_valores(primeiro, segundo):
    resultado = primeiro+segundo
    return resultado

valor_1 = 10 
valor_2 = 20

soma = soma_dois_valores(valor_1, valor_2)

print (soma)

30


In [2]:
lista_clientes = ['Joaquim', 'José', 'João', 'Maria']
lista_produtos = ['Maçã', 'Banana', 'Chocolate']

lista_clientes.append('Roberta')

print(lista_clientes[4])



Roberta


In [8]:
lista_vendas = []

venda = ('banana', 4, 8.0)

lista_vendas.append(venda)

print(venda)

print(venda[0])
print(venda[1])
print(venda[2])
print(f'\n{lista_vendas}')

('banana', 4, 8.0)
banana
4
8.0

[('banana', 4, 8.0)]


In [16]:
cliente_1 = {
    'nome': 'Joaquim',
    'idade': 34,
    'vip': True,
    'carteira': 345.99
}

cliente_2 = {
    'nome': 'Roberta',
    'idade': 26,
    'vip': False,
    'carteira': 1245.90
}

lista_clientes = [cliente_1, cliente_2]

print(lista_clientes)

[{'nome': 'Joaquim', 'idade': 34, 'vip': True, 'carteira': 345.99}, {'nome': 'Roberta', 'idade': 26, 'vip': False, 'carteira': 1245.9}]


In [17]:
import numpy as np

In [18]:
numpy_array = np.arange(0, 1_000_000 + 1, dtype='int64')

In [24]:
python_list = [i for i in range(1_000_000 + 1)]

python_list_square = [i**2 for i in python_list]

In [23]:
numpy_array_square = numpy_array**2

In [35]:
# criando um array
arr = np.array([1, 2, 3, 4, 5])
print(f"Elementos: {arr}, Tipo dos elementos: {arr.dtype}, Tamanho do array: {arr.shape}")

Elementos: [1 2 3 4 5], Tipo dos elementos: int64, Tamanho do array: (5,)


In [34]:
# acesso ao terceiro elemento do array (índice 2):
elemento = arr[2]
print(elemento)

3


In [33]:
# obtendo elementos de índice 1 a 3
subset = arr[1:4]
print(subset)

[2 3 4]


In [32]:
# Criando uma matriz
matrix = np.arange(1., 10).reshape((3, 3))
print(matrix)
print(f'Tipos dos elementos: {matrix.dtype}, Dimensões da matriz: {matrix.shape}')

[[1. 2. 3.]
 [4. 5. 6.]
 [7. 8. 9.]]
Tipos dos elementos: float64, Dimensões da matriz: (3, 3)


In [36]:
## acessando a 2 linha:
linha = matrix [1]
print(linha)

## acessando a 1 coluna:
coluna = matrix [:, 0]
print(coluna)

[4. 5. 6.]
[1. 4. 7.]


In [37]:
a = np.array([1.0, 2.0, 3.0])
b = 2.0

resultado = a*b
print(resultado)

[2. 4. 6.]


In [40]:
# multiplicação de matrizes
A = np.array([[1, 2],[3, 4], [5, 6]])
B = np.array([[1], [2]])

'''
print(f'lista de A:\n{A}')

print(f'lista de B:\n{B}')
'''



lista de A:
[[1 2]
 [3 4]
 [5 6]]
lista de B:
[[1]
 [2]]


In [41]:
## Multiplicação utilizando apenas listas python
C = [[0], [0], [0]]

for i in range(len(A)):
    for j in range(len(B[0])):
        for k in range(len(B)):
            C[i][j]+= A[i][k] * B[k][j]

print(C)

[[np.int64(5)], [np.int64(11)], [np.int64(17)]]


In [42]:
## agora vamos realizar a mesma operação com NumPy
D = A @ B
print(D)

[[ 5]
 [11]
 [17]]


In [47]:
N = 500

A = np.arange(N*N, dtype='int64').reshape(N, N)
B = A * 2

C = A @ B

print(C)
## Tempo de execucao: 0.196
## Memoria utilizada: 5.8 Mb

[[   41541750000    41541999500    41542249000 ...    41665751500
     41666001000    41666250500]
 [  103916750000   103917499500   103918249000 ...   104289251500
    104290001000   104290750500]
 [  166291750000   166292999500   166294249000 ...   166912751500
    166914001000   166915250500]
 ...
 [31041916750000 31042165499500 31042414249000 ... 31165545251500
  31165794001000 31166042750500]
 [31104291750000 31104540999500 31104790249000 ... 31228168751500
  31228418001000 31228667250500]
 [31166666750000 31166916499500 31167166249000 ... 31290792251500
  31291042001000 31291291750500]]


In [50]:
A_lst = A.tolist()
B_lst = B.tolist()
C_lst = np.zeros_like(A).tolist()

for i in range(len(A_lst)):
    for j in range(len(B_lst[0])):
        for k in range(len(B_lst)):
            C_lst[i][j] += A_lst[i][k] * B_lst[k][j]


## tempo de execução: 66.462s
## Memoria utilizada: 211.6 Mb

IOPub data rate exceeded.
The Jupyter server will temporarily stop sending output
to the client in order to avoid crashing it.
To change this limit, set the config variable
`--ServerApp.iopub_data_rate_limit`.

Current values:
ServerApp.iopub_data_rate_limit=1000000.0 (bytes/sec)
ServerApp.rate_limit_window=3.0 (secs)



In [54]:
import numpy as np

for i in range (6):
    for j in range (6):
        if(i > j):
            A[i][j] = "#"

print(A)


ValueError: invalid literal for int() with base 10: '#'